### ISSUE TITLE
TypeError: Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by markdawson** [mrphu3074/react-material-ui#48]
On my 1.4 Meteor app, after running the following installations:

`meteor add react`
`meteor add izzilab:material-ui`

I am getting this error when I try to launch it with `meteor`:

```
TypeError: Cannot read property 'displayName' of undefined
    at SourceProcessorSet.addLegacyHandler (/tools/isobuild/build-plugin.js:142:27)
    at /tools/isobuild/build-plugin.js:172:12
    at Function._.each._.forEach (/Users/markdawson/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at SourceProcessorSet.merge (/tools/isobuild/build-plugin.js:170:7)
    at /tools/isobuild/compiler.js:380:26
    at Array.forEach (native)
    at /tools/isobuild/compiler.js:376:26
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/compiler.js:372:16
    at /tools/isobuild/compiler.js:179:28
    at Object.withCache (/tools/fs/files.js:1585:12)
    at /tools/isobuild/compiler.js:178:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/markdawson/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:173:5)
    at /tools/isobuild/bundler.js:2624:24
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2567:31)
    at /tools/isobuild/bundler.js:2514:32
    at Object.withCache (/tools/fs/files.js:1585:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2514:16)
    at /tools/runners/run-app.js:582:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:572:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:625:35)
    at AppRunner._fiber (/tools/runners/run-app.js:884:28)
    at /tools/runners/run-app.js:402:12

```

I am working on a completely clean app with nothing else installed. Any potential workarounds?

**Comment by af6140** [comment]
Got same error.

**Comment by msyahidin** [comment]
got this error too today, are you still support this package?

**Comment by af6140** [comment]
Was able to work it out, does not know what exactly I did.

**Comment by MiceBishop** [comment]
I got the same error, pls help ???

**Comment by S7caapp** [comment]
Got the same error, but with other Meteor installations in a tutorial. Any solutions?
https://www.twilio.com/blog/2015/07/building-a-group-messaging-app-with-meteor-mongodb-and-twilio.html

**Comment by msyahidin** [comment]
You can try my "boilerplate" or just copy my package json and check meteor version. https://github.com/msyahidin/meteor-react-material

**Comment by trancehime** [comment]
Experiencing the same error after I updated from version 1.2.1 to 1.4.2.6; I had already rewritten my React code to extend React.Component instead of React.createClass, I have already attempted to refactor the code to use proper imports, but it won't even build properly thanks to this. Not entirely sure what the cause is either.

**Comment by mrphu3074** [comment]
I stopped maintain this package long time ago. Sorry about my moving. I will try to fix this problem.
